name: dice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/faces/
  
  fonts:
    - family: Sancreek Regular
      fonts:
        - asset: assets/fonts/Sancreek-Regular.ttf
    - family: PlayfairDisplay Regular
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
    - family: IBM Plex Serif
      fonts:
        - asset: assets/fonts/IBMPlexSerif-Regular.ttf
    - family: Inria Serif
      fonts:
        - asset: assets/fonts/InriaSerif-Regular.ttf